# server
# leave out the port as it is defined in server.port
server.endpoint: "http://localhost"
# options between 'dev', 'test' and 'prod'
server.env: "test"
server.port: ":9000"

# session
session.name: "gin-rest-prisma-boilerplate-session"

# redis
redis.idle_connections: 10
redis.network_type: "tcp"
redis.address: "localhost:6379"
redis.secret_key: "secret"
redis.password: ""

# prisma
prisma.endpoint: "http://localhost:4466"
